### PR TITLE
update dependabot #2

### PR DESCRIPTION
**Pull request by danmoseley**
Replacing https://github.com/dotnet/aspire-samples/pull/198 since I deleted my fork to test dependabot clean. (Maybe I should make a 2nd account just for this purpose)

Now updating NPM (and github actions) as well as Nuget. NPM ones are aggregated per-sample because merges of the lock file are hopeless.

On the test run, it timed out on nuget, but made PR's for the other two kinds: https://github.com/danmoseley/aspire-samples/pulls  .. my experience is that it will likely successfully make nuget PR's on a future run.

I haven't found a way to successfully move the .sln, but maybe that will emerge in future.

### CODE REVIEW

**Review by DamianEdwards — APPROVED** [review]
Thanks. I'm a bit concerned that the NPM samples have to be listed explicitly as that will easily become out of sync if any are added or removed in the future but I don't think we should block on that for now.

**Comment by danmoseley** [comment]
Right, I would need a dependabot expert to tell me whether there's a way to avoid it. It seems like it does require each package.lock explicitly.

**Comment by danmoseley** [comment]
BTW, the nuget leg is consistently timing out. A bigger problem than this repo. But it means that we should assume we own updating nuget dependencies. I'll have a shot at doing this manually now.

**Comment by DamianEdwards** [comment]
> BTW, the nuget leg is consistently timing out. A bigger problem than this repo. But it means that we should assume we own updating nuget dependencies. I'll have a shot at doing this manually now.

We assume that for now you mean? Otherwise, why did we add dependabot for NuGet at all?

Also we should fix #192 while we're doing this and remove CPM altogether.

**Comment by danmoseley** [comment]
>  Otherwise, why did we add dependabot for NuGet at all?

Because it periodically comes to life. We have been wrestling with this issue, with help from @brettfo , on dotnet/aspire and dotnet/eshop as well. It has gotten worse, but it's not caused by us; when it's fixed, dependencies will start updating without another PR. Meantime, the timing out is invisible to us.

**Pull request merged**
