### PR TITLE
Minor Grafana dashboard improvements

### PR DESCRIPTION
**Pull request by JamesNK**
Take 2 of https://github.com/dotnet/aspire-samples/pull/21

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
yes it's JSON :)

maybe PR's like this need before/after screenshots!

**Comment by DamianEdwards** [comment]
@JamesNK could you add as screenshot of the Grafana dashboard to the README?

**Comment by JamesNK** [comment]
The readme is displayed in samples. @IEvangelist are images supported in sample readmes? Is there a sample of a sample that has a screenshot sample?

Related, Aspire samples aren't in the [learn.microsoft.com samples browser](https://learn.microsoft.com/en-us/samples/browse/?terms=aspire) yet. Are wheels in motion to fix that?

**Comment by DamianEdwards** [comment]
@JamesNK it was @IEvangelist who asked me to add one to the eShopLite sample :smile: https://github.com/dotnet/aspire-samples/pull/15#discussion_r1385877676

**Review by danmoseley — APPROVED** [review]

**Comment by danmoseley** [comment]
my review got reset - I noticed we have "require signoffs on latest commit" -- I switched that off as we don't require that in aspire/aspnetcore

**Comment by IEvangelist** [comment]
> The readme is displayed in samples. @IEvangelist are images supported in sample readmes? Is there a sample of a sample that has a screenshot sample?
> 
> @IEvangelist Related, Aspire samples aren't in the [learn.microsoft.com samples browser](https://learn.microsoft.com/en-us/samples/browse/?terms=aspire) yet. Are wheels in motion to fix that?

Yes, the wheels are in motion. The Learn Platform team had to approve the new `ms.prod` metadata for `dontet-aspire` and once approved they ship it on Friday's. I knew we'd be blocked for a bit... but tomorrow they should be live! [Here's the latest status](https://github.com/MicrosoftDocs/samples/blob/main/dotnet/aspire-samples/.samples-status.json) showing that they are being picked up, but again, just needed to wait for the new metadata to flow through.

As for an example with images, yeah - of course, all standard MD:

- https://github.com/dotnet/samples/blob/main/orleans/Voting/README.md
- https://learn.microsoft.com/en-us/samples/dotnet/samples/orleans-voting-sample-app-on-kubernetes/

**Pull request merged**
