### PR TITLE
Utilize injected ports

### PR DESCRIPTION
**Pull request by sammychinedu2ky**
The Silo port and Gateway port are already injected as Environmental Variables
```
Orleans__Endpoints__GatewayPort
Orleans__Endpoints__SiloPort
```

### CODE REVIEW

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson

**Comment by sammychinedu2ky** [comment]
@DamianEdwards

**Comment by sammychinedu2ky** [comment]
@IEvangelist

**Review by IEvangelist — APPROVED** [review]

**Review by ReubenBond — APPROVED** [review]

**Comment by ReubenBond** [comment]
Thank you, @sammychinedu2ky!

**Pull request merged**
