### PR TITLE
Add tsaconfig to enable compliance tooling

### PR DESCRIPTION
**Pull request by danmoseley**
Copy https://github.com/dotnet/extensions/pull/5285

@mmitche I believe aspire-samples needs to have compliance tools run as we're treating it as prod. BUT it doesn't use arcade. Will this still trigger the tooling we want?

### CODE REVIEW

**Comment by danmoseley** [comment]
OK @mmitche this is now correct, even though this isn't arcade, right?

**Comment by danmoseley** [comment]
Although, perhaps we should wait to figure this out: https://github.com/dotnet/aspire/pull/4860#issuecomment-2229858139

**Comment by danmoseley** [comment]
```
 2024-07-20T15:05:01.3202017+00:00 info [Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler] starting process...	{"Executable": {"name":"frontend_388fa2f-njdc1rg"}, "Reconciliation": 9, "executable": "/home/runner/work/aspire-samples/aspire-samples/dotnet/dotnet"}
 2024-07-20T15:05:01.3296123+00:00 info [Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler] process started	{"Executable": {"name":"frontend_388fa2f-njdc1rg"}, "Reconciliation": 9, "executable": "/home/runner/work/aspire-samples/aspire-samples/dotnet/dotnet", "PID": 16197}
 2024-07-20T15:05:01.3909222+00:00 Resource 'basketcache' log: 2024-07-20T15:05:00.352975525Z 1:C 20 Jul 2024 15:05:00.351 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
 2024-07-20T15:05:01.3909592+00:00 Resource 'basketcache' log: 2024-07-20T15:05:00.353020248Z 1:C 20 Jul 2024 15:05:00.351 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
 2024-07-20T15:05:01.3909639+00:00 Resource 'basketcache' log: 2024-07-20T15:05:00.353027872Z 1:C 20 Jul 2024 15:05:00.351 * Redis version=7.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
 2024-07-20T15:05:01.3909681+00:00 Resource 'basketcache' log: 2024-07-20T15:05:00.353033242Z 1:C 20 Jul 2024 15:05:00.351 * Configuration loaded
 2024-07-20T15:05:01.3909728+00:00 Resource 'basketcache' log: 2024-07-20T15:05:00.353037951Z 1:M 20 Jul 2024 15:05:00.352 * monotonic clock: POSIX clock_gettime
 2024-07-20T15:05:01.3909764+00:00 Resource 'basketcache' log: 2024-07-20T15:05:00.353042930Z 1:M 20 Jul 2024 15:05:00.352 * Running mode=standalone, port=6379.
 2024-07-20T15:05:01.3909800+00:00 Resource 'basketcache' log: 2024-07-20T15:05:00.353047880Z 1:M 20 Jul 2024 15:05:00.352 * Server initialized
 2024-07-20T15:05:01.3909834+00:00 Resource 'basketcache' log: 2024-07-20T15:05:00.353052689Z 1:M 20 Jul 2024 15:05:00.352 * Ready to accept connections tcp
 2024-07-20T15:05:01.4552776+00:00 Resource 'catalogservice' log: 2024-07-20T15:05:01.3832615 \x1b[41m\x1b[30mfail\x1b[39m\x1b[22m\x1b[49m: Microsoft.Extensions.Hosting.Internal.Host[11]
 2024-07-20T15:05:01.4553084+00:00 Resource 'catalogservice' log:       Hosting failed to start
 2024-07-20T15:05:01.4553121+00:00 Resource 'catalogservice' log:       System.IO.IOException: Failed to bind to address http://[::1]:40725: address already in use.
 2024-07-20T15:05:01.4553160+00:00 Resource 'catalogservice' log:        ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 2024-07-20T15:05:01.4553194+00:00 Resource 'catalogservice' log:        ---> System.Net.Sockets.SocketException (98): Address already in use
 2024-07-20T15:05:01.4553237+00:00 Resource 'catalogservice' log:          at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
 2024-07-20T15:05:01.4553273+00:00 Resource 'catalogservice' log:          at System.Net.Sockets.Socket.Bind(EndPoint localEP)
 2024-07-20T15:05:01.4553306+00:00 Resource 'catalogservice' log:          at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
```

**Comment by mmitche** [comment]
You enabled the 1ESPT compliance tooling, so yes it should work.

**Review by mmitche — APPROVED** [review]

**Pull request merged**
