### PR TITLE
macosx gitignore

### PR DESCRIPTION
**Pull request by moljac**
Just extra patterns to be ignored on MacOSX

### CODE REVIEW

**Comment by DamianEdwards** [comment]
Thanks for this. Thinking about who can review this. Tagging some macOS users I know @ellismg @captainsafia

**Comment by moljac** [comment]
@DamianEdwards 

Take your time. I work mostly on Macs, so we can cover as much platforms as possible and those files are a bit annoying.

I am investigating clients (MAUI as no.1) and will ping you soon with tons of questions.

**Comment by captainsafia** [comment]
This is a good minimum set for macOS. If you want to be extra thorough, I'd recommend copying the [macOS.gitignore template from GitHub's catalog](https://github.com/github/gitignore/blob/main/Global/macOS.gitignore).

**Comment by DamianEdwards** [comment]
Thanks @captainsafia! @moljac would you like to copy those over too?

**Comment by moljac** [comment]
> Thanks @captainsafia! 

Thanks. 

> @moljac would you like to copy those over too?

sure.

**Review by DamianEdwards — APPROVED** [review]

**Pull request merged**
